Updated toDataURL encoderOptions value to be passed as Number
sportheroes/aurelia-image-resizer pull request #12
Opened 2018-04-30 03:26 UTC by nuxy

Fix to resolve issue https://github.com/sportheroes/aurelia-image-resizer/issues/11

2018-04-30 07:26 UTC, hadrienl approved these changes
Thanks :)

2018-04-30 07:30 UTC, hadrienl requested changes

2018-04-30 07:30 UTC, hadrienl commented on src/image-resizer/image-resizer.js
> +        this.output = this.canvas.toDataURL(this.type, Number(this.encoderOptions));
If no `encoderOptions` attribute is passed, value will be 0 : `Number(undefined) === 0`. Please test if value is a string before transforming it to number.

2018-04-30 08:32 UTC, nuxy commented
Updated to check for the following:
- `encoder-options=""` is defined (empty `string`)
- `encoder-options` is not defined (value is `null`)

2018-04-30 14:28 UTC, hadrienl requested changes

2018-04-30 14:28 UTC, hadrienl commented on src/image-resizer/image-resizer.js
> +        let encoderOpts = (this.encoderOptions !== 'string' && this.encoderOptions !== null)
Try

```
const encoderOptions = ['string', 'number'].includes(typeof this.encoderOptions)
? Number(this.encoderOptions)
: null;
```

2018-05-02 08:31 UTC, hadrienl approved these changes
👍🏼

2018-05-02 08:32 UTC, merged